schema = 3

[mod]
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.1"
    hash = "sha256-rTWqbtC+EVz4fT2HmDWpucUTMtQyraInPYf2hlG8/pM="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.0"
    hash = "sha256-sW90eNnxmYBGY+uQe9tH97CCHdRvNuseWhicySnKlDo="
  [mod."github.com/diamondburned/adaptive"]
    version = "v0.0.2-0.20221227093656-fa139be203a8"
    hash = "sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw="
  [mod."github.com/diamondburned/arikawa/v3"]
    version = "v3.3.1-0.20230609054540-4224b93c4e01"
    hash = "sha256-zDmcpqeJMEf0Qd0kOFkKKNhCASxNwBsh+fUOwsl1LFM="
  [mod."github.com/diamondburned/chatkit"]
    version = "v0.0.0-20230904043742-66a46d3d2a92"
    hash = "sha256-1b97e2JEebvUenoMnMiSufkCXo5mVBgeyRz1IiOtTiY="
  [mod."github.com/diamondburned/gotk4-adwaita/pkg"]
    version = "v0.0.0-20230307040502-bfe82926e1be"
    hash = "sha256-jp2KeXza45zFCNvcEpA2UrOYZKLHQrU4+3A7SSRsuCc="
  [mod."github.com/diamondburned/gotk4/pkg"]
    version = "v0.0.6-0.20230825053034-ad325703aa2e"
    hash = "sha256-47LA2OAz5aWD9Yjv27yAlQxxlDfjByRvmyXapS6vy/8="
  [mod."github.com/diamondburned/gotkit"]
    version = "v0.0.0-20230924233657-9446c13efb7b"
    hash = "sha256-HyvW12EDMccTokgMv+KpP2S2iRZqGXF/jO/iaQ/GQsY="
  [mod."github.com/diamondburned/ningen/v3"]
    version = "v3.0.1-0.20230908225032-f3dbe02c7c8d"
    hash = "sha256-rHaVhuQ68U1wHQ/kDJbzpGi0ZSamJlpE3ikK8XItaWg="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/enescakir/emoji"]
    version = "v1.0.0"
    hash = "sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.0.6"
    hash = "sha256-fpaNRLf+qZy6Sk3Uas2H9fpxkVNkOCY1EcHcIZCAPr8="
  [mod."github.com/gorilla/schema"]
    version = "v1.2.0"
    hash = "sha256-fENDYTtMBGAgJB7rv0o61KyoO81mibJycLifazazd1E="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/ianlancetaylor/cgosymbolizer"]
    version = "v0.0.0-20220405231054-a1ae3e4bba26"
    hash = "sha256-gQ5SUjHpX82+Eke8znuweBL/yzaVQQV06eLH91gTfcI="
  [mod."github.com/kylelemons/godebug"]
    version = "v1.1.0"
    hash = "sha256-DJ0re9mGqZb6PROQI8NPC0JVyDHdZ/y4uehNH7MbczY="
  [mod."github.com/leonelquinteros/gotext"]
    version = "v1.5.3-0.20230829162019-37f474cfb069"
    hash = "sha256-ylBa3NtdtkgqEAhsXdYBTyhUUSU7e5NpHfw6Wq7cwbU="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/twmb/murmur3"]
    version = "v1.1.3"
    hash = "sha256-3r/AQgj6Xw4GczIkwmX2JPOM8qqH6Oh5oUM4P/lVMQM="
  [mod."github.com/yalue/merged_fs"]
    version = "v1.2.3"
    hash = "sha256-qj+AMOjdFRFoUj9KIKLIBd3DenicUtF2tBEWYZ5zyIY="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.6"
    hash = "sha256-+yAEKuRtXHX2THh3XMSG6UPcPPU0sSz5H5taH9Mx1Jc="
  [mod."github.com/zalando/go-keyring"]
    version = "v0.2.1"
    hash = "sha256-F4G03wV1GeLucqJIOXVN4htEETfGzIVAsBTU1iNLxlA="
  [mod."go4.org"]
    version = "v0.0.0-20200411211856-f5505b9728dd"
    hash = "sha256-UxbUjyr/bArM+3XAQfQ58XBbePvUdZ31EiQkCfXl/i0="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20230525183740-e7c30c78aeb2"
    hash = "sha256-IDQleFabPVMsuiCrYNPBNNDOvl+JrKQTrsmbZy4vtlA="
  [mod."golang.org/x/crypto"]
    version = "v0.1.0"
    hash = "sha256-0oZWBSiW5Pd/2a1p2beuoelDe0CpfXZhrg/qPduJlYs="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220902085622-e7cb96979f69"
    hash = "sha256-yVdEVP3jBVOYd4ADvz9UHQfju9Hhh9Xr9TE9kfHJGbw="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20220722155255-886fb9371eb4"
    hash = "sha256-ZZyIlxh+nqsOiWHstW7eHXN7RhHnbSL2eDIzcve07Q0="
  [mod."golang.org/x/text"]
    version = "v0.4.0"
    hash = "sha256-JvyMygdmTvWg7xhbnUB9MMk6WcYXJt8DAj4DYl82Pys="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
