schema = 3

[mod]
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.1"
    hash = "sha256-rTWqbtC+EVz4fT2HmDWpucUTMtQyraInPYf2hlG8/pM="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.0"
    hash = "sha256-sW90eNnxmYBGY+uQe9tH97CCHdRvNuseWhicySnKlDo="
  [mod."github.com/diamondburned/adaptive"]
    version = "v0.0.2-0.20221227093656-fa139be203a8"
    hash = "sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw="
  [mod."github.com/diamondburned/arikawa/v3"]
    version = "v3.2.1-0.20230131081350-00c3ed4b8afd"
    hash = "sha256-xCa728dZdTmuW4nK494wgg80dj+eKwsxhwVMIb+xyTo="
  [mod."github.com/diamondburned/chatkit"]
    version = "v0.0.0-20230209113202-230dd95a8aae"
    hash = "sha256-ptX4Ee2qw75TmxQyJ9Xee/B1dRp/DYgY/i960m2du6s="
  [mod."github.com/diamondburned/gotk4-adwaita/pkg"]
    version = "v0.0.0-20230105075138-e92a3b568c9e"
    hash = "sha256-JmaETZ1hvQt/AG5mrdDCVgXqxhVugmg6OwMS6QB1dgA="
  [mod."github.com/diamondburned/gotk4/pkg"]
    version = "v0.0.5-0.20230105054822-f46414fdaa94"
    hash = "sha256-oTVQQ0n5QyAIwYL+TQ5lAfpyLpSyIBdAHtYa1+9Xnnw="
  [mod."github.com/diamondburned/gotkit"]
    version = "v0.0.0-20230131094355-0f2a6e285d1e"
    hash = "sha256-RqKS4KL7vPgPPOn3SVFlyLPvNXV5ERgAwSfI1jYhEaM="
  [mod."github.com/diamondburned/ningen/v3"]
    version = "v3.0.1-0.20230124093205-d39554fd5d67"
    hash = "sha256-WV3i3pj4uE3s0X4nXiWhUGf7tLKksJHvajuBm7EB5Ko="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/enescakir/emoji"]
    version = "v1.0.0"
    hash = "sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.0.6"
    hash = "sha256-fpaNRLf+qZy6Sk3Uas2H9fpxkVNkOCY1EcHcIZCAPr8="
  [mod."github.com/gorilla/schema"]
    version = "v1.2.0"
    hash = "sha256-fENDYTtMBGAgJB7rv0o61KyoO81mibJycLifazazd1E="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/ianlancetaylor/cgosymbolizer"]
    version = "v0.0.0-20220405231054-a1ae3e4bba26"
    hash = "sha256-gQ5SUjHpX82+Eke8znuweBL/yzaVQQV06eLH91gTfcI="
  [mod."github.com/kylelemons/godebug"]
    version = "v1.1.0"
    hash = "sha256-DJ0re9mGqZb6PROQI8NPC0JVyDHdZ/y4uehNH7MbczY="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/twmb/murmur3"]
    version = "v1.1.3"
    hash = "sha256-3r/AQgj6Xw4GczIkwmX2JPOM8qqH6Oh5oUM4P/lVMQM="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.13"
    hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="
  [mod."github.com/zalando/go-keyring"]
    version = "v0.2.1"
    hash = "sha256-F4G03wV1GeLucqJIOXVN4htEETfGzIVAsBTU1iNLxlA="
  [mod."go4.org"]
    version = "v0.0.0-20200411211856-f5505b9728dd"
    hash = "sha256-UxbUjyr/bArM+3XAQfQ58XBbePvUdZ31EiQkCfXl/i0="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20220617031537-928513b29760"
    hash = "sha256-i2BRLeOXm2WrtWPTlZw3AqatwANlkXDEmK2LJvRqtWs="
  [mod."golang.org/x/crypto"]
    version = "v0.1.0"
    hash = "sha256-0oZWBSiW5Pd/2a1p2beuoelDe0CpfXZhrg/qPduJlYs="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220902085622-e7cb96979f69"
    hash = "sha256-yVdEVP3jBVOYd4ADvz9UHQfju9Hhh9Xr9TE9kfHJGbw="
  [mod."golang.org/x/mod"]
    version = "v0.6.0"
    hash = "sha256-qaHIt9MYuTTfaKtbeVqBVI+Pcv60SMQuhkkjFQObx48="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20220601150217-0de741cfad7f"
    hash = "sha256-HqEv10lJ4TAv7tnx6P0SBDD1YUIb7VinmBIkXDYOWcA="
  [mod."golang.org/x/sys"]
    version = "v0.1.0"
    hash = "sha256-nZbEJ/2PuWrDLD4ujeVvcFGoIsfVoIH/Lcp4FjD7hpU="
  [mod."golang.org/x/text"]
    version = "v0.4.0"
    hash = "sha256-JvyMygdmTvWg7xhbnUB9MMk6WcYXJt8DAj4DYl82Pys="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."golang.org/x/tools"]
    version = "v0.2.0"
    hash = "sha256-T6+3oa41rN1o7izlmV2pHqON3f4mw7hjYC/GMjzPqc8="
