schema = 3

[mod]
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.1"
    hash = "sha256-rTWqbtC+EVz4fT2HmDWpucUTMtQyraInPYf2hlG8/pM="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.0"
    hash = "sha256-sW90eNnxmYBGY+uQe9tH97CCHdRvNuseWhicySnKlDo="
  [mod."github.com/diamondburned/adaptive"]
    version = "v0.0.2-0.20221227093656-fa139be203a8"
    hash = "sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw="
  [mod."github.com/diamondburned/arikawa/v3"]
    version = "v3.2.1-0.20230210050458-2c379c90c2ac"
    hash = "sha256-0+XVAhJly35aKnCR+pz/orEY/pSPEMGLxs7KWZc8Fpc="
  [mod."github.com/diamondburned/chatkit"]
    version = "v0.0.0-20230209213000-7d9bb654be2f"
    hash = "sha256-Wb2VCeWF0qor0xwifNiyETcsaikhqXDHP+zqdtMUrLI="
  [mod."github.com/diamondburned/gotk4-adwaita/pkg"]
    version = "v0.0.0-20230307050941-20a05fa3a9df"
    hash = "sha256-+EK5Vh8CpIayRUumKA0he1qENbHjkhNaCWrBvlP6pcQ="
  [mod."github.com/diamondburned/gotk4/pkg"]
    version = "v0.0.5-0.20230307013122-e86c9b44a4bf"
    hash = "sha256-Ev4J8NylVnhGhTM9Ujgd7wWtGixDFtPVXptJxXZsFOo="
  [mod."github.com/diamondburned/gotkit"]
    version = "v0.0.0-20230307054845-dc8ab38b9db4"
    hash = "sha256-aQ+T2Ab7mmigeCzbfRhDRojJCh3UapBkT+SSEex6THs="
  [mod."github.com/diamondburned/ningen/v3"]
    version = "v3.0.1-0.20230124093205-d39554fd5d67"
    hash = "sha256-WV3i3pj4uE3s0X4nXiWhUGf7tLKksJHvajuBm7EB5Ko="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/enescakir/emoji"]
    version = "v1.0.0"
    hash = "sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.0.6"
    hash = "sha256-fpaNRLf+qZy6Sk3Uas2H9fpxkVNkOCY1EcHcIZCAPr8="
  [mod."github.com/gorilla/schema"]
    version = "v1.2.0"
    hash = "sha256-fENDYTtMBGAgJB7rv0o61KyoO81mibJycLifazazd1E="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/ianlancetaylor/cgosymbolizer"]
    version = "v0.0.0-20220405231054-a1ae3e4bba26"
    hash = "sha256-gQ5SUjHpX82+Eke8znuweBL/yzaVQQV06eLH91gTfcI="
  [mod."github.com/kylelemons/godebug"]
    version = "v1.1.0"
    hash = "sha256-DJ0re9mGqZb6PROQI8NPC0JVyDHdZ/y4uehNH7MbczY="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/twmb/murmur3"]
    version = "v1.1.3"
    hash = "sha256-3r/AQgj6Xw4GczIkwmX2JPOM8qqH6Oh5oUM4P/lVMQM="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.13"
    hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="
  [mod."github.com/zalando/go-keyring"]
    version = "v0.2.1"
    hash = "sha256-F4G03wV1GeLucqJIOXVN4htEETfGzIVAsBTU1iNLxlA="
  [mod."go4.org"]
    version = "v0.0.0-20200411211856-f5505b9728dd"
    hash = "sha256-UxbUjyr/bArM+3XAQfQ58XBbePvUdZ31EiQkCfXl/i0="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20230209150437-ee73d164e760"
    hash = "sha256-8XYjkQgoL9FCM5Ivvohtkx45VHE5zzbUZLez5scbmww="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210921155107-089bfa567519"
    hash = "sha256-62Qtoqu7AxoxpZFd+75qXC0naixAct3rWsJd0nSgMCU="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220902085622-e7cb96979f69"
    hash = "sha256-yVdEVP3jBVOYd4ADvz9UHQfju9Hhh9Xr9TE9kfHJGbw="
  [mod."golang.org/x/mod"]
    version = "v0.6.0-dev.0.20220419223038-86c51ed26bb4"
    hash = "sha256-HS5GtzK6mLkQ/FM+GWoX4wSW0XllHK/2O3Y7O2/sFBk="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20220601150217-0de741cfad7f"
    hash = "sha256-HqEv10lJ4TAv7tnx6P0SBDD1YUIb7VinmBIkXDYOWcA="
  [mod."golang.org/x/sys"]
    version = "v0.1.0"
    hash = "sha256-nZbEJ/2PuWrDLD4ujeVvcFGoIsfVoIH/Lcp4FjD7hpU="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."golang.org/x/tools"]
    version = "v0.1.11"
    hash = "sha256-osT8kqiICYhllI3xJHXquP3SYPIXSq/ByRMpUg+IDSM="
